#!/bin/sh
# SPDX-FileCopyrightText: 2026 Frank Martínez <mnesarco at gmail>
# SPDX-License-Identifier: GPL-3.0-or-later
set -e

HERE="$(dirname "$(readlink -f "$0")")"

export LD_LIBRARY_PATH="$HERE/usr/bin/lib:$HERE/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="$HERE/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

exec "$HERE/usr/bin/freecad_launcher" "$@"
