import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

// This file will be generated by drift_dev
part 'database.g.dart';

class Apps extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
  TextColumn get command => text()();
  TextColumn get args => text()();
  TextColumn get kind => text()();
  TextColumn get cwd => text()();
}

class Profiles extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
  TextColumn get args => text()();
  TextColumn get cwd => text()();
}

class DownloadedAddons extends Table {
  TextColumn get name => text()();
  TextColumn get repoUrl => text().nullable()();
  TextColumn get zipUrl => text().nullable()();
  TextColumn get branch => text().nullable()();
  TextColumn get version => text().nullable()();
  DateTimeColumn get updatedAt => dateTime()();
  DateTimeColumn get downloadedAt => dateTime()();
  TextColumn get downloadedName => text()();

  @override
  Set<Column<Object>> get primaryKey => {repoUrl, zipUrl, branch, version, updatedAt};
}

@DriftDatabase(tables: [Apps, Profiles, DownloadedAddons])
class Database extends _$Database {
  Database() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      if (from < 2) {
        // Migration Code
      }
    },
  );

  Future<int> addApp(AppsCompanion entry) => into(apps).insert(entry);
  Future<int> addProfile(ProfilesCompanion entry) => into(profiles).insert(entry);
  Future<int> addAddonDownload(DownloadedAddonsCompanion entry) =>
      into(downloadedAddons).insertOnConflictUpdate(entry);

  Stream<List<DownloadedAddon>> watchAddonDownloads(String addonName, String? branch) {
    final query = select(downloadedAddons);
    query.where((t) => t.name.equals(addonName));
    if (branch != null) {
      query.where((t) => t.branch.equals(branch));
    }
    query.orderBy([(u) => OrderingTerm.asc(u.updatedAt)]);
    return query.watch();
  }

  // READ (Watch provides a Stream for reactivity)
  Stream<List<App>> watchApps(String filter) {
    final query = select(apps);
    if (filter.isNotEmpty) {
      query.where((t) => t.name.contains(filter));
    }
    query.orderBy([(u) => OrderingTerm.asc(u.name)]);
    return query.watch();
  }

  // READ (Watch provides a Stream for reactivity)
  Stream<List<Profile>> watchProfiles(String filter) {
    final query = select(profiles);
    if (filter.isNotEmpty) {
      query.where((t) => t.name.contains(filter));
    }
    query.orderBy([(u) => OrderingTerm.asc(u.name)]);
    return query.watch();
  }

  // UPDATE
  Future<bool> updateApp(App entry) => update(apps).replace(entry);
  Future<bool> updateProfile(Profile entry) => update(profiles).replace(entry);

  // DELETE
  Future<int> deleteApp(int id) => (delete(apps)..where((t) => t.id.equals(id))).go();
  Future<int> deleteProfile(int id) => (delete(profiles)..where((t) => t.id.equals(id))).go();

  Future<DownloadedAddon?> findLatestDownloadedAddon(String name, String? branch) {
    final query = select(downloadedAddons)
      ..where((a) => a.name.equals(name))
      ..orderBy([(u) => OrderingTerm.desc(u.updatedAt)])
      ..limit(1);
    if (branch == null) {
      query.where((a) => a.branch.isNull());
    } else {
      query.where((a) => a.branch.equals(branch));
    }
    return query.getSingleOrNull();
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dataRoot = await getApplicationSupportDirectory();
    final folder = Directory(dataRoot.path);

    if (!await folder.exists()) await folder.create(recursive: true);

    final file = File(p.join(folder.path, 'data.sqlite'));
    return NativeDatabase(file);
  });
}
