import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

// This file will be generated by drift_dev
part 'database.g.dart';

class Apps extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
  TextColumn get command => text()();
  TextColumn get args => text()();
  TextColumn get kind => text()();
  TextColumn get cwd => text()();
}

class Profiles extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
  TextColumn get args => text()();
  TextColumn get cwd => text()();
}

@DriftDatabase(tables: [Apps, Profiles])
class Database extends _$Database {
  Database() : super(_openConnection());

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      if (from < 2) {
        await m.createTable(profiles);
      }
    },
  );

  Future<int> addApp(AppsCompanion entry) => into(apps).insert(entry);
  Future<int> addProfile(ProfilesCompanion entry) => into(profiles).insert(entry);

  // READ (Watch provides a Stream for reactivity)
  Stream<List<App>> watchApps(String filter) {
    final query = select(apps);
    if (filter.isNotEmpty) {
      query.where((t) => t.name.contains(filter));
    }
    query.orderBy([(u) => OrderingTerm.asc(u.name)]);
    return query.watch();
  }

  // READ (Watch provides a Stream for reactivity)
  Stream<List<Profile>> watchProfiles(String filter) {
    final query = select(profiles);
    if (filter.isNotEmpty) {
      query.where((t) => t.name.contains(filter));
    }
    query.orderBy([(u) => OrderingTerm.asc(u.name)]);
    return query.watch();
  }

  // UPDATE
  Future<bool> updateApp(App entry) => update(apps).replace(entry);
  Future<bool> updateProfile(Profile entry) => update(profiles).replace(entry);

  // DELETE
  Future<int> deleteApp(int id) => (delete(apps)..where((t) => t.id.equals(id))).go();
  Future<int> deleteProfile(int id) => (delete(profiles)..where((t) => t.id.equals(id))).go();
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dataRoot = await getApplicationSupportDirectory();
    final folder = Directory(p.join(dataRoot.path, 'freecad_launcher'));

    if (!await folder.exists()) await folder.create(recursive: true);

    final file = File(p.join(folder.path, 'data.sqlite'));
    return NativeDatabase(file);
  });
}
