// SPDX-FileCopyrightText: 2026 Frank Martínez <mnesarco at gmail>
// SPDX-License-Identifier: GPL-3.0-or-later

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

// Run from the repository root: dart run tool/generate_third_party_notices.dart
const List<String> _bundledLibraries = [
  'libharfbuzz.so.0 — MIT (https://github.com/harfbuzz/harfbuzz)',
  'libfreetype.so.6 — FreeType License or GPL-2.0-or-later (https://freetype.org)',
  'libfontconfig.so.1 — MIT-style (https://gitlab.freedesktop.org/fontconfig/fontconfig)',
  'libexpat.so.1 — MIT (https://github.com/libexpat/libexpat)',
  'libz.so.1 — zlib (https://zlib.net)',
  'libuuid.so.1 — BSD-3-Clause (https://github.com/util-linux/util-linux)',
  'libfribidi.so.0 — LGPL-2.1-or-later (https://github.com/fribidi/fribidi)',
  'libgmp.so.10 — LGPL-3.0-or-later or GPL-2.0-or-later (https://gmplib.org)',
  'libcom_err.so.2 — MIT (https://github.com/tytso/e2fsprogs)',
  'libgpg-error.so.0 — LGPL-2.1-or-later (https://www.gnupg.org/software/libgpg-error)',
  'libICE.so.6 / libSM.so.6 — MIT (https://gitlab.freedesktop.org/xorg/lib)',
];

void main() {
  final depsResult = Process.runSync('dart', ['pub', 'deps', '--json']);
  if (depsResult.exitCode != 0) {
    stderr.writeln('dart pub deps --json failed: ${depsResult.stderr}');
    exitCode = 1;
    return;
  }

  final deps = jsonDecode(depsResult.stdout as String) as Map<String, dynamic>;
  final roots = _packageRoots();
  final rawPackages = (deps['packages'] as List).cast<Map<String, dynamic>>();
  final byName = {for (final raw in rawPackages) raw['name'] as String: raw};
  final shipped = <String>{};
  final queue = <String>[
    for (final raw in rawPackages)
      if (raw['kind'] == 'direct') raw['name'] as String,
  ];
  while (queue.isNotEmpty) {
    final name = queue.removeLast();
    if (!shipped.add(name)) {
      continue;
    }
    for (final dependency in (byName[name]?['dependencies'] as List? ?? const [])) {
      queue.add(dependency as String);
    }
  }

  final packages = <_Package>[];
  for (final raw in rawPackages) {
    final name = raw['name'] as String;
    if (!shipped.contains(name)) {
      continue;
    }
    final root = roots[name];
    if (root == null) {
      continue;
    }
    packages.add(
      _Package(name: name, version: raw['version'] as String?, licenseFile: _findLicenseFile(root)),
    );
  }

  packages.sort((a, b) => a.name.toLowerCase().compareTo(b.name.toLowerCase()));

  final groups = <String, List<_Package>>{};
  final unlicensed = <_Package>[];
  for (final package in packages) {
    final file = package.licenseFile;
    if (file == null) {
      unlicensed.add(package);
      continue;
    }
    final text = file.readAsStringSync().replaceAll('\r\n', '\n').trimRight();
    groups.putIfAbsent(text, () => []).add(package);
  }

  final buffer = StringBuffer()
    ..writeln('# Third-party notices')
    ..writeln()
    ..writeln(
      'FreeCAD Launcher is licensed under the GNU General Public License v3.0 or later '
      '(see `LICENSE`). The application redistributes the third-party components listed '
      'below.',
    )
    ..writeln()
    ..writeln('Copyright 2026 Frank Martínez <mnesarco at gmail>.')
    ..writeln()
    ..writeln(
      'Generated by `dart run tool/generate_third_party_notices.dart`. Do not edit by hand.',
    )
    ..writeln()
    ..writeln('## Bundled system libraries')
    ..writeln()
    ..writeln(
      'The Linux AppImage bundles the following libraries in addition to the system '
      'baseline (see `packaging/appimage/build_appimage.sh`):',
    )
    ..writeln();
  for (final library in _bundledLibraries) {
    buffer.writeln('- $library');
  }
  final sevenZipLicense = File('third_party/7zip/license.txt')
      .readAsStringSync()
      .replaceAll('\r\n', '\n')
      .trimRight();
  buffer
    ..writeln()
    ..writeln('## Bundled executables')
    ..writeln()
    ..writeln(
      'The Windows portable build bundles the official 7-Zip standalone console '
      'executable `third_party/7zip/7zr.exe` (SHA-256 '
      '`ad4c82fadcbdf93c03b4fc440f300509c7d60c5c2f4d183e35d9d70d6957037d`, 602,624 bytes), '
      'used to extract the official FreeCAD `.7z` archives. 7-Zip is licensed under '
      'LGPL-2.1-or-later; the unRAR restriction does not apply because `7zr` contains no '
      'RAR code.',
    )
    ..writeln()
    ..writeln('```text')
    ..writeln(sevenZipLicense)
    ..writeln('```')
    ..writeln()
    ..writeln('## Microsoft Visual C++ runtime')
    ..writeln()
    ..writeln(
      'The Windows portable build bundles the Microsoft Visual C++ runtime DLLs app-local '
      '(next to `freecad_launcher.exe`), so the launcher starts without a system-wide Visual C++ '
      'Redistributable install. The files are copied unmodified from the Microsoft Visual Studio '
      'redistributable folder (`Microsoft.VC*.CRT`, x64) of the toolchain used to build the '
      'release, including `concrt140.dll`, `msvcp140.dll`, `msvcp140_1.dll`, `msvcp140_2.dll`, '
      '`msvcp140_atomic_wait.dll`, `msvcp140_codecvt_ids.dll`, `vccorlib140.dll`, '
      '`vcruntime140.dll` and `vcruntime140_1.dll`. Copyright Microsoft Corporation. '
      'Redistributed as Distributable Code by app-local deployment under the Microsoft Visual '
      'Studio license terms; see '
      '<https://learn.microsoft.com/cpp/windows/redistributing-visual-cpp-files>.',
    )
    ..writeln()
    ..writeln('## FreeCAD trademark')
    ..writeln()
    ..writeln(
      'FreeCAD and the FreeCAD logo are trademarks of the FreeCAD Project Association '
      'AISBL. The launcher bundles the official FreeCAD logo (`assets/images/freecad-logo.svg`, '
      'from the official FreeCAD AppImage) unmodified, for attribution in the About dialog '
      'only; the FreeCAD application itself is installed by the user from official sources. '
      'See <https://www.freecad.org>.',
    )
    ..writeln()
    ..writeln('## Dart and Flutter packages')
    ..writeln()
    ..writeln('| Package | Version | License file |')
    ..writeln('|---|---|---|');
  for (final package in packages) {
    final license = package.licenseFile == null
        ? 'not found'
        : p.basename(package.licenseFile!.path);
    buffer.writeln('| ${package.name} | ${package.version ?? '—'} | $license |');
  }
  if (unlicensed.isNotEmpty) {
    buffer
      ..writeln()
      ..writeln('Packages without a bundled license file:')
      ..writeln();
    for (final package in unlicensed) {
      buffer.writeln('- ${package.name} ${package.version ?? ''}'.trimRight());
    }
  }
  buffer
    ..writeln()
    ..writeln('## License texts')
    ..writeln();
  final sortedGroups = groups.entries.toList()
    ..sort((a, b) => a.value.first.name.toLowerCase().compareTo(b.value.first.name.toLowerCase()));
  for (final group in sortedGroups) {
    final appliesTo = group.value
        .map((package) => '${package.name} ${package.version ?? ''}'.trimRight())
        .join(', ');
    final firstLine = group.key
        .split('\n')
        .map((line) => line.trim())
        .firstWhere((line) => line.isNotEmpty, orElse: () => 'License');
    buffer
      ..writeln('### ${p.basename(group.value.first.licenseFile!.path)} — $firstLine')
      ..writeln()
      ..writeln('Applies to: $appliesTo')
      ..writeln()
      ..writeln('```text')
      ..writeln(group.key)
      ..writeln('```')
      ..writeln();
  }

  File('THIRD_PARTY_NOTICES.md').writeAsStringSync(buffer.toString());
  stdout.writeln(
    'Wrote THIRD_PARTY_NOTICES.md: ${packages.length} packages, '
    '${groups.length} distinct license texts.',
  );
}

class _Package {
  _Package({required this.name, required this.version, required this.licenseFile});

  final String name;
  final String? version;
  final File? licenseFile;
}

Map<String, String> _packageRoots() {
  final configFile = File(p.join('.dart_tool', 'package_config.json'));
  if (!configFile.existsSync()) {
    return const {};
  }
  final config = jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
  final projectRoot = Directory.current.absolute.path;
  final roots = <String, String>{};
  for (final raw in (config['packages'] as List).cast<Map<String, dynamic>>()) {
    final rootUri = raw['rootUri'] as String;
    if (!rootUri.startsWith('file:')) {
      continue;
    }
    final root = p.normalize(Directory.fromUri(Uri.parse(rootUri)).absolute.path);
    if (p.equals(root, projectRoot)) {
      continue;
    }
    roots[raw['name'] as String] = root;
  }
  return roots;
}

File? _findLicenseFile(String root) {
  var directory = Directory(root);
  for (var depth = 0; depth < 4; depth++) {
    final found = _licenseIn(directory);
    if (found != null) {
      return found;
    }
    final parent = directory.parent;
    if (p.equals(parent.path, directory.path)) {
      break;
    }
    directory = parent;
  }
  return null;
}

File? _licenseIn(Directory directory) {
  if (!directory.existsSync()) {
    return null;
  }
  final candidates = <String>[];
  for (final entity in directory.listSync()) {
    if (entity is! File) {
      continue;
    }
    final name = p.basename(entity.path).toLowerCase();
    if (name.startsWith('license') || name.startsWith('copying')) {
      candidates.add(entity.path);
    }
  }
  if (candidates.isEmpty) {
    return null;
  }
  int rank(String path) {
    final name = p.basename(path).toLowerCase();
    if (name == 'license') {
      return 0;
    }
    if (name == 'copying') {
      return 1;
    }
    return 2;
  }

  candidates.sort((a, b) {
    final byRank = rank(a).compareTo(rank(b));
    return byRank != 0 ? byRank : a.toLowerCase().compareTo(b.toLowerCase());
  });
  return File(candidates.first);
}
